// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feed_follows.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const createFeedFollow = `-- name: CreateFeedFollow :one
WITH insert_feed_follow AS (INSERT INTO feed_follows (id, created_at, updated_at, user_id, feed_id)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
RETURNING id, created_at, updated_at, user_id, feed_id)
SELECT insert_feed_follow.id, insert_feed_follow.created_at, insert_feed_follow.updated_at, insert_feed_follow.user_id, insert_feed_follow.feed_id, users.name AS user_name, feeds.name AS feed_name
FROM insert_feed_follow
LEFT JOIN users
ON users.id = insert_feed_follow.user_id
LEFT JOIN feeds
ON feeds.id = insert_feed_follow.feed_id
`

type CreateFeedFollowParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

type CreateFeedFollowRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	UserName  sql.NullString
	FeedName  sql.NullString
}

func (q *Queries) CreateFeedFollow(ctx context.Context, arg CreateFeedFollowParams) (CreateFeedFollowRow, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollow,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i CreateFeedFollowRow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
		&i.UserName,
		&i.FeedName,
	)
	return i, err
}

const getFeedFollowsForUserID = `-- name: GetFeedFollowsForUserID :many
SELECT feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id, users.name AS user_name, feeds.name AS feed_name
FROM feed_follows
LEFT JOIN users
ON users.id = feed_follows.user_id
LEFT JOIN feeds
ON feeds.id = feed_follows.feed_id
WHERE feed_follows.user_id = $1
`

type GetFeedFollowsForUserIDRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	UserName  sql.NullString
	FeedName  sql.NullString
}

func (q *Queries) GetFeedFollowsForUserID(ctx context.Context, userID uuid.UUID) ([]GetFeedFollowsForUserIDRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollowsForUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsForUserIDRow
	for rows.Next() {
		var i GetFeedFollowsForUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.UserName,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFeedFollows = `-- name: ListFeedFollows :many
SELECT feed_follows.id, feed_follows.created_at, feed_follows.updated_at, feed_follows.user_id, feed_follows.feed_id, users.name AS user_name, feeds.name AS feed_name
FROM feed_follows
LEFT JOIN users
ON users.id = feed_follows.user_id
LEFT JOIN feeds
ON feeds.id = feed_follows.feed_id
`

type ListFeedFollowsRow struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
	UserName  sql.NullString
	FeedName  sql.NullString
}

func (q *Queries) ListFeedFollows(ctx context.Context) ([]ListFeedFollowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listFeedFollows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedFollowsRow
	for rows.Next() {
		var i ListFeedFollowsRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
			&i.UserName,
			&i.FeedName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resetFeedFollow = `-- name: ResetFeedFollow :exec
DELETE FROM feed_follows
`

func (q *Queries) ResetFeedFollow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, resetFeedFollow)
	return err
}

const unFollow = `-- name: UnFollow :exec
DELETE FROM feed_follows
WHERE user_id = $1 AND feed_id = $2
`

type UnFollowParams struct {
	UserID uuid.UUID
	FeedID uuid.UUID
}

func (q *Queries) UnFollow(ctx context.Context, arg UnFollowParams) error {
	_, err := q.db.ExecContext(ctx, unFollow, arg.UserID, arg.FeedID)
	return err
}
